---
title: "Mini-Project 2"
author: "Your Name Here"
date: "October 31, 2017"
output:
  html_document:
    code_folding: hide
---


## Loading the data

This project is so interesting and relevant to my life!

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(scales)
library(gridExtra)
```

## Creating table to aggregate all contributions to each candidate, over all recorded years
```{r, message = FALSE, warning = FALSE}
# joining tables to align candidate IDs with relevant information on campaign contributions
con_can <- candidates %>%
  inner_join(contributions, by = "cand_id") %>%
  select(fec_id = cand_id, cand_name, cand_party_affiliation, cand_election_yr, cand_office_district,cand_st1, cand_city, cand_state, cand_zip, cmte_id, committee_name = name, committee_city = city, committee_state = state, transaction_dt, transaction_amt, tran_id) %>%
  # ommission of rows with missing data
  na.omit()
  
```

## Testing some functions
```{r fig.width = 20, fig.height = 10, message = FALSE, warning = FALSE}

# function to further refine table by state
cut_down_table <- function(state_arg){
  con_can %>%
  filter(cand_state == state_arg) %>%
  group_by(fec_id, cand_election_yr) %>%
  # summary of total money received by candidate, as well as total number of committees contributing
  summarize( money_sum = sum(transaction_amt), total_com = n_distinct(committee_name))
}

# function to join with house_elections to provide information on election year and result
join_for_wins  <- function(state_arg){
  cut_down_table(state_arg) %>%
  inner_join(house_elections, by = "fec_id") %>%
    select(fec_id, money_sum, total_com, state, incumbent, candidate_name, party, ge_winner)
    # include only Democrats and Republicans
    # filter(party == "D" | party == "R")
}

# function to generate individual plots
state_plot <- function(state_arg){
  join_for_wins(state_arg) %>%
    ggplot(aes(x = total_com, y = money_sum, fill = ge_winner)) + 
    geom_point(position = position_jitter(width = 1, height = 0.5), shape = 21, color = "transparent", size = 3) + 
    scale_fill_manual(values = c(W = "orange", N = "blue")) + 
    stat_smooth(method = lm, se = TRUE, fullrange = TRUE, aes(fill = ge_winner, color = ge_winner), show.legend = TRUE) + 
    ggtitle(state_arg) +
    theme(plot.title = element_text(size = 40, face = "bold")) + 
    scale_y_continuous(labels = dollar) + 
    ylab("Total Funds Received") + 
    theme(axis.title.y = element_text(margin = margin(r = 30), size = 30)) + 
    theme(axis.text.y = element_text(size = 20)) +
    xlab("Total Committees Donating") +
    theme(axis.title.x = element_text(size = 30)) + 
    theme(legend.title = element_blank()) +
    scale_color_manual(values = c(W = "orange", N = "blue"))
}

# defining populous states to plot for
populous_states <- c("TX",
                     "CA",
                     "NY",
                     "PA",
                     "IL",
                     "OH")

# making a list of all plots
swing_grid <- lapply(populous_states, state_plot)

# arranging all plots into a grid for viewing
do.call("grid.arrange", c(swing_grid, ncol = 3))

```

